package hu.bhr.crm.repository;

import hu.bhr.crm.repository.entity.TaskEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Repository
public interface TaskRepository extends JpaRepository<TaskEntity, UUID> {

    /**
     * Atomically sets the 'completed_at' timestamp to the database's current time
     * if the task's status matches the provided value.
     * <p>
     * This method uses a native SQL query to:
     * <ul>
     * <li>Avoid race conditions by performing the check and update atomically.</li>
     * <li>Use the database server's time ({@code CURRENT_TIMESTAMP}) instead of the application's time
     * to ensure consistency and avoid clock skew issues.</li>
     * <li>Return the generated timestamp immediately using the {@code RETURNING} clause.</li>
     * </ul>
     * Note: This query utilizes database-specific syntax (CAST to ENUM type).
     * </p>
     *
     * @param id the unique UUID of the task
     * @param status the string representation of the status to check against
     * @return the timestamp generated by the database at the moment of update, or null if no row was updated
     */
    @Query(
        value = """
            UPDATE task
            SET completed_at = CURRENT_TIMESTAMP
            WHERE id = :id AND status = CAST(:status AS status)
            RETURNING completed_at""",
    nativeQuery = true)
    Instant setCompletedAtIfCompleted(@Param("id") UUID id, @Param("status") String status);

    List<TaskEntity> findAllByCustomerId(UUID customerId);
}
